//
//  DashboardPresenter.swift
//  ProofOfConcept
//
//  Created by Yuvraj Sorav on 05/03/20.
//  Copyright (c) 2020 Yuvraj Sorav. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DashboardPresentationLogic
{
    func presentSomething(response: Dashboard.Something.Response)
    func presentDashboardData(_ dashboardDict : DashboardModel)
}

class DashboardPresenter: DashboardPresentationLogic
{
    weak var viewController: DashboardDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Dashboard.Something.Response)
    {
        let viewModel = Dashboard.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentDashboardData(_ dashboardDict : DashboardModel) {
        viewController?.displayDashboardData(dashboardDict)
    }
}
